version: "3.9"

services:
    app:
        container_name: snowtopiamappagecon
        image: snowtopiamappageimg
        build:
            context: .
            dockerfile: dockerfile
        restart: always
        ports:
            - "8080:8080"