FROM nginx:alpine
RUN apk add bash icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib
RUN apk add libgdiplus --repository https://dl-3.alpinelinux.org/alpine/edge/testing/
RUN apk add bash icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib wget
RUN apk add libgdiplus --repository https://dl-3.alpinelinux.org/alpine/edge/testing/
RUN mkdir -p /usr/share/dotnet \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet
RUN wget https://dot.net/v1/dotnet-install.sh
RUN chmod +x dotnet-install.sh
RUN ./dotnet-install.sh -c 6.0 --install-dir /usr/share/dotnet
RUN ./dotnet-install.sh -c Current --runtime aspnetcore
RUN apk add --no-cache python3 py3-pip
RUN pip install beautifulsoup4
WORKDIR /web/
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY . /web/
RUN /bin/bash -c 'chmod +x /web/app/Process.py'
CMD crond -l 2 -f